---

- hosts: robot

  pre_tasks:
    - name: Install docker py
      pip:
        name: docker
      become: true
      
  roles:
    - role: ansible-role-ros-adafruitmotorhat

  tasks:
    - name: Check that robot is online
      ping: