---

- name: Start ROS velocity muxer docker container
  docker_container:
    name: ros_vel_muxer
    image: "frankjoshua/ros-vel-muxer:{{ cpu_arch }}"
    network_mode: "host"
    restart_policy: "unless-stopped"
    env:
      ROS_MASTER_URI: "{{ ros_master_uri }}"
      ROS_IP: "{{ ros_ip }}"
    command: "python /node.py --computer_topic {{ computer_topic }} --manual_topic {{ manual_topic }} --output_topic {{ output_topic }} --delay 5 -x {{ x_speed_multiplier }} -z {{ z_speed_multiplier }} "