---

- name: Start ROS velocity muxer docker container
  docker_container:
    name: ros_vel_muxer
    image: "frankjoshua/ros-vel-muxer:{{ cpu_arch }}"
    network_mode: "host"
    restart_policy: "unless-stopped"
    env:
      ROS_MASTER_URI: "{{ ros_master_uri }}"
      ROS_IP: "{{ ros_ip }}"
    command: "python /node.py --computer_topic /cmd_vel/computer --manual_topic /pocketbot/cmd_vel --output_topic /cmd_vel --delay 5 -x 0.2 -z 0.2"